load("@pip_packages//:requirements.bzl", "all_requirements")

py_binary(
    name = "ipython",
    srcs = ["ipython.py"],
    deps = all_requirements,
)

py_binary(
    name = "jupyter",
    srcs = ["jupyter.py"],
    deps = all_requirements,
)
